### ISSUE TITLE
Group actions for complex groups

### ISSUE THREAD

**Issue by joansola** [artivis/manif#291] opened 2024-03-21 10:59 UTC
Complex groups are `SE(3)`, `SE_2(3)`, `Sgal(3)`.

I was thinking, regarding `act()` in all complex groups. Maybe we could have special actions. In case e.g. of `SGal3`, we would have:

- transform points: `T+R*p`
- boost: see Kelly's paper
- event-transform: see paper

and other possible actions only available for this group.

In SE3 we have a similar problem, in 
- transforming points `T+R*p`
- and transforming vetors `R*v`

In `manif` we already have some examples on non-abstracted methods:

- `asSO3()` <-- for `SE3`, `SE23`, `SGal3`
- `E6()` <-- for the generators

so I see no fundamental impediment for `act()`. In fact, it is possible that `act()` as an abstract form is not convenient, precisely because actions are not pre-defined operations for Lie groups in their abstract form.

**Comment by artivis** [comment] 2024-03-21 11:15
Isn't this a duplicate of https://github.com/artivis/manif/issues/119?
If so, could you update #119 with this comment and close this ticket?

**Closed** 2024-05-14 00:40 UTC
